[package]
name = "gst-rerunsink"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description = "gstreamer sink element for rerun"

[dependencies]
glib = "0.20"
gst = { package = 'gstreamer', version = "0.23" }
gst-base = { package = 'gstreamer-base', version = "0.23" }
gst-video = { package = "gstreamer-video", version = "0.23" }
once_cell = "1"
rerun = { version = "0.25.1", features = ["native_viewer"] }
thiserror = "2.0"

[lib]
crate-type = ["rlib", "cdylib"]

[build-dependencies]
gst-plugin-version-helper = "0.8"
